version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU
install:
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
before_build:
- cmd: nuget restore -DisableParallelProcessing source/TimeLapser.sln
build:
  parallel: true
  verbosity: normal
artifacts:
- path: source/TimeLapser/bin/Release
  name: GH
deploy:
- provider: GitHub
  auth_token:
    secure: MfE4qSIr2yoNR8/GUgRVJgaM9jVupDe40JAgb5P/Es/bD6DGzuqkTrHnzpsIFTPH
  artifact: GH